/**
 * VVId (VId), Vivek's Id or Vivek's virtual Id is a technique  or algorithm to generate 
 * unique, random, trackless & storageless(no storage is required to keep track of them) IDs (strings, numbers, symbols etc.).
 *     Copyright (C) 2020  Vivek Mangla
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 * 
 *     To connect with author, possible way to reach is via email 
 *     vivek.funeesh@gmail.com 
 * */

package com.vivek.vVidLib.models;

import java.math.BigInteger;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * For Sequencer, value will not be modified/processed. Only valueAsString and
 * valueInBits will be processed. Value will act like a raw base constantly
 * increasing, later on upon which various shuffling mechanisms would act using
 * the property of box-preservation-of-shuffled-bits for a given range.
 */
@Data
@EqualsAndHashCode(callSuper = false)
@NoArgsConstructor
public class Sequencer extends CommonFields {

	/** Original Value generated by Sequencer */
	private BigInteger value;

	private SequencerChoice seqC;

	private int initialNumberOfSymbols;
}
